# Generated by Django 3.2 on 2024-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('scity', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='E_model',
        ),
    ]
